# Git
alias gst="git status"
alias gco="git checkout"
alias gcom="git checkout master"
alias gci="git commit"
alias glg="git lg"
alias gh="git help"
alias gpl="git pull"
alias gpull="git pull"
alias gps="git push"
alias gpush="git push"
alias gplom="git pull origin master"
#alias gpsom="git push origin master"
alias gcl="git clone"
alias gbr="git branch"
alias gdf="git diff"
alias gdiff="git diff"
alias grbm="git rebase master"
alias gft="git fetch"
alias gadd="git add"
alias gstash="git stash"
alias gshow="git show"
alias grst="git reset"
# Commented out next line because it was causing error messages when opening a new shell
# alias gpfo="git push -f origin $(git rev-parse --abbrev-ref HEAD)"
alias gclone="git clone"

# Vagrant
alias vpr="vagrant provision"
alias vsh="vagrant ssh"
alias vup="vagrant up"
alias vhalt="vagrant halt"

alias mvimdiff="mvim -d"
